# Generated by Django 5.1.2 on 2024-11-13 22:13

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL)),
                ('tutorNo', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(choices=[('ruby_on_rails', 'Ruby on Rails'), ('python', 'Python'), ('javascript', 'Javascript'), ('c_plus_plus', 'C++'), ('c_sharp', 'C#'), ('react', 'React'), ('angular', 'Angular'), ('vue_js', 'Vue.js'), ('node_js', 'Node.js'), ('express_js', 'Express.js'), ('django', 'Django'), ('flask', 'Flask'), ('spring', 'Spring'), ('hibernate', 'Hibernate'), ('jpa', 'JPA'), ('sql', 'SQL'), ('mongodb', 'MongoDB'), ('postgresql', 'PostgreSQL'), ('mysql', 'MySQL'), ('git', 'Git')], max_length=100)),
                ('bio', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('tutorials.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('ruby_on_rails', 'Ruby on Rails'), ('python', 'Python'), ('javascript', 'Javascript'), ('c_plus_plus', 'C++'), ('c_sharp', 'C#'), ('react', 'React'), ('angular', 'Angular'), ('vue_js', 'Vue.js'), ('node_js', 'Node.js'), ('express_js', 'Express.js'), ('django', 'Django'), ('flask', 'Flask'), ('spring', 'Spring'), ('hibernate', 'Hibernate'), ('jpa', 'JPA'), ('sql', 'SQL'), ('mongodb', 'MongoDB'), ('postgresql', 'PostgreSQL'), ('mysql', 'MySQL'), ('git', 'Git')], max_length=100)),
                ('frequency', models.CharField(choices=[('weekly', 'Weekly'), ('fortnightly', 'Fortnightly'), ('every other week', 'Every other week')], max_length=20)),
                ('term', models.CharField(choices=[('September-Christmas', 'September-Christmas'), ('January-Easter term', 'January-Easter'), ('May-July', 'May-July')], max_length=50)),
                ('duration', models.IntegerField(choices=[(60, '1 hour'), (120, '2 hours')], default=60)),
                ('start_date', models.DateField()),
                ('day_of_week', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10)),
                ('start_time', models.CharField(choices=[('09:00', '9:00 AM'), ('10:00', '10:00 AM'), ('11:00', '11:00 AM'), ('12:00', '12:00 PM'), ('13:00', '1:00 PM'), ('14:00', '2:00 PM'), ('15:00', '3:00 PM'), ('16:00', '4:00 PM'), ('17:00', '5:00 PM')], default='09:00', max_length=5)),
                ('location', models.CharField(default='Online', max_length=100)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('pending', 'Pending'), ('confirmed', 'Confirmed')], default='requested', max_length=20)),
                ('invoice_paid', models.BooleanField(default=False)),
                ('price_per_term', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('tutor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='tutorials.tutor')),
            ],
        ),
    ]
