# Generated by Django 5.1.2 on 2024-12-10 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutorials", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="student",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="sum",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="topic",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="tutor",
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="invoice_paid",
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="location",
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="price_per_term",
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="start_date",
        ),
        migrations.RemoveField(
            model_name="student",
            name="current_term_end_date",
        ),
        migrations.RemoveField(
            model_name="student",
            name="current_term_lesson_time",
        ),
        migrations.RemoveField(
            model_name="student",
            name="current_term_start_date",
        ),
        migrations.RemoveField(
            model_name="student",
            name="current_term_tutor",
        ),
        migrations.RemoveField(
            model_name="student",
            name="preferred_language",
        ),
        migrations.RemoveField(
            model_name="student",
            name="preferred_lesson_duration",
        ),
        migrations.RemoveField(
            model_name="student",
            name="preferred_lesson_frequency",
        ),
        migrations.RemoveField(
            model_name="student",
            name="preferred_tutor",
        ),
        migrations.RemoveField(
            model_name="student",
            name="proficiency_level",
        ),
        migrations.RemoveField(
            model_name="tutor",
            name="subject",
        ),
        migrations.RemoveField(
            model_name="tutor",
            name="timings",
        ),
        migrations.AddField(
            model_name="invoice",
            name="totalsum",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="lesson",
            name="invoiceNo",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tutorials.invoice",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="frequency",
            field=models.CharField(
                choices=[("weekly", "Weekly"), ("fortnightly", "Fortnightly")],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="start_time",
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="status",
            field=models.CharField(
                choices=[
                    ("Rejected", "Rejected"),
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("late", "Late"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("resolved", "Resolved")],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "admin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tutorials.admin",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="tutorials.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Subjects",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "proficiency_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Beginner", "Beginner"),
                            ("Novice", "Novice"),
                            ("Intermediate", "Intermediate"),
                            ("Advanced", "Advanced"),
                            ("Mastery", "Mastery"),
                        ],
                        default="Intermediate",
                        max_length=12,
                        null=True,
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        choices=[
                            ("ruby_on_rails", "Ruby on Rails"),
                            ("python", "Python"),
                            ("javascript", "Javascript"),
                            ("c_plus_plus", "C++"),
                            ("c_sharp", "C#"),
                            ("react", "React"),
                            ("angular", "Angular"),
                            ("vue_js", "Vue.js"),
                            ("node_js", "Node.js"),
                            ("express_js", "Express.js"),
                            ("django", "Django"),
                            ("flask", "Flask"),
                            ("spring", "Spring"),
                            ("hibernate", "Hibernate"),
                            ("jpa", "JPA"),
                            ("sql", "SQL"),
                            ("mongodb", "MongoDB"),
                            ("postgresql", "PostgreSQL"),
                            ("mysql", "MySQL"),
                            ("git", "Git"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "proficiency",
                    models.CharField(
                        choices=[
                            ("Beginner", "Beginner"),
                            ("Novice", "Novice"),
                            ("Intermediate", "Intermediate"),
                            ("Advanced", "Advanced"),
                            ("Mastery", "Mastery"),
                        ],
                        default="Intermediate",
                        max_length=12,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TutorAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("monday", "Monday"),
                            ("tuesday", "Tuesday"),
                            ("wednesday", "Wednesday"),
                            ("thursday", "Thursday"),
                            ("friday", "Friday"),
                            ("saturday", "Saturday"),
                            ("sunday", "Sunday"),
                        ],
                        max_length=10,
                    ),
                ),
                ("starttime", models.TimeField()),
                ("endtime", models.TimeField()),
                (
                    "tutor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tutorials.tutor",
                    ),
                ),
            ],
        ),
    ]
