# Generated by Django 5.1.2 on 2024-12-02 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_alter_lesson_tutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='price_per_class',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=10),
        ),
    ]
