# Generated by Django 5.1.2 on 2024-11-25 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_admin_tutor_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='proficiency_level',
            field=models.CharField(blank=True, choices=[('Beginner', 'Beginner'), ('Novice', 'Novice'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Mastery', 'Mastery')], default='Intermediate', max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='user',
            name='type_of_user',
            field=models.CharField(choices=[('admin', 'Admin'), ('tutor', 'Tutor'), ('student', 'Student')], default='student', max_length=20),
        ),
    ]
