# Generated by Django 5.1.2 on 2024-11-25 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_alter_lesson_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='status',
            field=models.CharField(choices=[('Rejected', 'Rejected'), ('pending', 'Pending'), ('confirmed', 'Confirmed')], default='Pending', max_length=20),
        ),
    ]
