# Generated by Django 5.1.2 on 2024-11-25 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0003_student_proficiency_level_user_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='tutorNo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
