# Generated by Django 5.1.2 on 2024-12-02 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0003_lesson_price_per_class'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='sum',
            new_name='total_sum',
        ),
    ]
